# Generated by Django 4.2.4 on 2023-08-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0002_adminlogin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminLogin',
        ),
    ]
