# Generated by Django 4.2.4 on 2023-08-14 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0004_hosteldata2_backlog_hosteldata3_backlog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata3',
            name='Backlog',
            field=models.CharField(default='NO', max_length=3),
        ),
    ]
