# Generated by Django 4.2.4 on 2023-08-14 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0005_alter_hosteldata3_backlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata3',
            name='Backlog',
            field=models.CharField(default='YES', max_length=3),
        ),
    ]
