# Generated by Django 4.2.4 on 2023-08-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0006_alter_hosteldata3_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata2',
            name='Nu_Backlog',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='Nu_Backlog',
            field=models.IntegerField(default=0),
        ),
    ]
