# Generated by Django 4.2.4 on 2023-08-23 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0009_remove_hosteldata1_id1_remove_hosteldata2_id2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata2',
            name='Branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hosteldata2',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
    ]
