# Generated by Django 4.2.4 on 2023-08-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0010_alter_hosteldata2_branch_alter_hosteldata2_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata1',
            name='Branch',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='hosteldata1',
            name='Email',
            field=models.EmailField(max_length=30),
        ),
    ]
