# Generated by Django 4.2.4 on 2023-08-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0012_hosteldata1_fno1_hosteldata2_fno2_hosteldata3_fno3'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata3',
            name='remark',
            field=models.CharField(default='NA', max_length=50),
        ),
    ]
