# Generated by Django 4.2.4 on 2023-08-30 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0013_hosteldata3_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hosteldata3',
            name='remark',
            field=models.CharField(default='NA', max_length=200),
        ),
    ]
