# Generated by Django 4.2.4 on 2023-09-12 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0014_alter_hosteldata3_remark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lists',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p3', models.FileField(default='file.pdf', upload_to='lists/')),
                ('f3', models.FileField(default='file.pdf', upload_to='lists/')),
                ('p2', models.FileField(default='file.pdf', upload_to='lists/')),
                ('f2', models.FileField(default='file.pdf', upload_to='lists/')),
                ('p1', models.FileField(default='file.pdf', upload_to='lists/')),
                ('f1', models.FileField(default='file.pdf', upload_to='lists/')),
            ],
        ),
    ]
