# Generated by Django 4.2.4 on 2023-09-12 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0015_lists'),
    ]

    operations = [
        migrations.AddField(
            model_name='lists',
            name='k',
            field=models.IntegerField(default=101010),
        ),
    ]
