# Generated by Django 4.2.4 on 2023-11-11 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0017_hosteldata1_remark_hosteldata2_remark'),
    ]

    operations = [
        migrations.AddField(
            model_name='hosteldata1',
            name='Enroll',
            field=models.CharField(default='2107067', max_length=10),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='SPhoto',
            field=models.FileField(default='file.jpg', upload_to='3signatures/student/'),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='city1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='city2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='occupation',
            field=models.CharField(default='farmer', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='pincode1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='pincode2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='shift',
            field=models.CharField(default='shift1', max_length=8),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='state1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='state2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='street1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata1',
            name='street2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='Enroll',
            field=models.CharField(default='2107067', max_length=10),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='SPhoto',
            field=models.FileField(default='file.jpg', upload_to='3signatures/student/'),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='city1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='city2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='occupation',
            field=models.CharField(default='farmer', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='pincode1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='pincode2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='shift',
            field=models.CharField(default='shift1', max_length=8),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='state1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='state2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='street1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata2',
            name='street2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='Enroll',
            field=models.CharField(default='2107067', max_length=10),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='SPhoto',
            field=models.FileField(default='file.jpg', upload_to='3signatures/student/'),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='city1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='city2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='occupation',
            field=models.CharField(default='farmer', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='pincode1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='pincode2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='shift',
            field=models.CharField(default='shift1', max_length=8),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='state1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='state2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='street1',
            field=models.CharField(default='Dummy', max_length=50),
        ),
        migrations.AddField(
            model_name='hosteldata3',
            name='street2',
            field=models.CharField(default='Dummy', max_length=50),
        ),
    ]
