# Generated by Django 4.2.4 on 2023-11-13 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hostel_Addmission', '0019_alter_hosteldata1_enroll_alter_hosteldata1_city1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hosteldata1',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='pincode1',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='pincode2',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='state2',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='hosteldata1',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='pincode1',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='pincode2',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='state2',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='hosteldata2',
            name='street2',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='city1',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='city2',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='pincode1',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='pincode2',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='state1',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='state2',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='street1',
        ),
        migrations.RemoveField(
            model_name='hosteldata3',
            name='street2',
        ),
        migrations.AlterField(
            model_name='hosteldata2',
            name='Enroll',
            field=models.CharField(max_length=10),
        ),
    ]
